blueprint:
  name: "[HVAC] Controlo Excedente Solar - Ligar Ar Condicionado"
  description: Ligar Modo Aquecimento do Ar condicionado com Excedente Solar

  domain: automation
  input:
    hvac_unit:
      name: Unidade a Controlar
      selector:
        entity:
          domain: climate
          multiple: true

    hvac_mode_heat:
      name: Modo Calor
      default: true
      selector:
        boolean:

    schedule_end:
      name: Horário de fim de controlo
      description: Horário da acção
      selector:
        time:

    hvac_temperature:
      name: Temperatura do AC
      default: 20
      selector:
        number:
          step: 0.5
          min: 18
          max: 26

    temperature_sensor:
      name: Sensor de Temperatura
      default:
      selector:
        entity:
          domain: sensor
          device_class: temperature

    window_sensor:
      name: Sensor da Janelas
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: window

    room_temperature:
      name: Temperatura da Divisão
      default: 20
      selector:
        number:
          min: 18
          max: 25
          step: 0.1
          unit_of_measurement: "ºC"

    room_temperature_diff:
      name: Diferença para a Referência
      default: 0
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "ºC"

    selected_season:
      name: Estação do Ano
      default: [spring, summer, autumn, winter]
      selector:
        select:
          options:
            - label: Primavera
              value: spring
            - label: Verão
              value: summer
            - label: Outono
              value: autumn
            - label: Inverno
              value: winter
          custom_value: false
          multiple: true

mode: restart
max_exceeded: silent

variables:
  hvac_temperature: !input hvac_temperature
  hvac_mode_heat: !input hvac_mode_heat
  room_temperature: !input room_temperature
  room_temperature_diff: !input room_temperature_diff

trigger:
  - trigger: state
    entity_id: binary_sensor.notify_home
    to: 'off'
    from: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0

  - trigger: numeric_state
    entity_id: !input temperature_sensor
    below: !input room_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.temperature_outside
    below: !input room_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.temperature_outside
    above: !input room_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.deye_inverter_pv_power_average
    above: 1500
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.house_power_consumption_average
    below: 2000
    for:
      minutes: 10

condition:
  - condition: state
    entity_id: input_boolean.automation_bypass_hvac
    state: "off"

  - condition: state
    entity_id: binary_sensor.notify_home
    state: "off"

  - condition: state
    entity_id: input_boolean.extended_away_mode
    state:
      - "off"

  - condition: state
    entity_id: !input hvac_unit
    state:
      - "off"

  - condition: numeric_state
    entity_id: sensor.deye_inverter_pv_power_average
    above: 1500

  - condition: numeric_state
    entity_id: sensor.house_power_consumption_average
    below: 2000

  - condition: state
    entity_id: sensor.season
    state: !input "selected_season"

  - condition: time
    before: !input schedule_end

  - alias: "Window Closed"
    condition: state
    entity_id: !input window_sensor
    state: "off"

  - alias: "Run once a day (wait at least 12 hours)"
    condition: template
    value_template: >
      {% set hours = 12 %}
      {% set last = state_attr(this.entity_id, 'last_triggered') %}
      {{ last is none or (now() - last).total_seconds() > hours * 3600 }}

  - condition: or
    conditions:
      - condition: and
        conditions:
          - "{{ hvac_mode_heat == true }}"
          - condition: numeric_state
            entity_id: !input temperature_sensor
            below: !input room_temperature
          - condition: numeric_state
            entity_id: sensor.temperature_outside
            below: !input room_temperature
          - condition: template
            value_template: "{{ (states('input_number.house_target_low_temperature') | float - states(room_temperature) | float) >= room_temperature_diff  }}"
      - condition: and
        conditions:
          - "{{ hvac_mode_heat == false }}"
          - condition: numeric_state
            entity_id: !input temperature_sensor
            above: !input room_temperature
          - condition: template
            value_template: "{{ (states(room_temperature) | float - states('input_number.house_target_high_temperature') | float) >= room_temperature_diff }}"

action:
  - if:
      - "{{ hvac_mode_heat == true }}"
    then:
      - action: climate.set_hvac_mode
        target:
          entity_id: !input hvac_unit
        data:
          hvac_mode: heat
    else:
      - action: climate.set_hvac_mode
        target:
          entity_id: !input hvac_unit
        data:
          hvac_mode: cool

  - action: climate.set_temperature
    target:
      entity_id: !input hvac_unit
    data:
      temperature: !input hvac_temperature

  - action: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: !input hvac_unit

  - action: climate.set_swing_mode
    data:
      swing_mode: swing
    target:
      entity_id: !input hvac_unit