blueprint:
  name: "[HVAC] Controlo Excedente Solar - Ligar Ar Condicionado"
  description: Ligar Modo Aquecimento do Ar condicionado com Excedente Solar

  domain: automation
  input:
    hvac_unit:
      name: Unidade a Controlar
      selector:
        entity:
          domain: climate
          multiple: true

    temperature_sensor:
      name: Sensor de Temperatura
      default:
      selector:
        entity:
          domain: sensor
          device_class: temperature

    window_sensor:
      name: Sensor da Janelas
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: window

    selected_season:
      name: Estação do Ano
      default: [spring, summer, autumn, winter]
      selector:
        select:
          options:
            - label: Primavera
              value: spring
            - label: Verão
              value: summer
            - label: Outono
              value: autumn
            - label: Inverno
              value: winter
          custom_value: false
          multiple: true

mode: restart
max_exceeded: silent

variables:
  temperature_sensor: !input temperature_sensor

trigger:
  - trigger: state
    entity_id: binary_sensor.notify_home
    to: 'off'
    from: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0

  - trigger: numeric_state
    entity_id: !input temperature_sensor
    below: input_number.house_target_low_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: !input temperature_sensor
    below: input_number.house_target_high_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.temperature_outside
    below: input_number.house_target_low_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.temperature_outside
    above: input_number.house_target_high_temperature
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.deye_inverter_pv_power_average
    above: 1500
    for:
      minutes: 10

  - trigger: numeric_state
    entity_id: sensor.house_power_consumption_average
    below: 2000
    for:
      minutes: 10

condition:
  - condition: state
    entity_id: input_boolean.automation_bypass_hvac
    state: "off"

  - condition: state
    entity_id: binary_sensor.notify_home
    state: "off"

  - condition: state
    entity_id: input_boolean.extended_away_mode
    state:
      - "off"

  - condition: state
    entity_id: !input hvac_unit
    state:
      - "off"

  - condition: numeric_state
    entity_id: sensor.deye_inverter_pv_power_average
    above: 1500

  - condition: numeric_state
    entity_id: sensor.house_power_consumption_average
    below: 2000

  - condition: state
    entity_id: sensor.season
    state: !input "selected_season"

  - alias: "Window Closed"
    condition: state
    entity_id: !input window_sensor
    state: "off"

  - alias: "Not cleaning mode"
    condition: state
    entity_id: calendar.cleaning
    state: "off"

  - alias: "Run once every two hours"
    condition: template
    value_template: >
      {% set hours = 2 %}
      {% set last = state_attr(this.entity_id, 'last_triggered') %}
      {{ last is none or (now() - last).total_seconds() > hours * 3600 }}

  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ (states('input_number.house_target_low_temperature') | float - states(temperature_sensor) | float) > 0  }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ (states(temperature_sensor) | float - states('input_number.house_target_high_temperature') | float) > 0 }}"

action:
  - if:
      - condition: numeric_state
        entity_id: !input temperature_sensor
        below: input_number.house_target_low_temperature
    then:
      - action: climate.set_hvac_mode
        target:
          entity_id: !input hvac_unit
        data:
          hvac_mode: heat
      - action: climate.set_temperature
        target:
          entity_id: !input hvac_unit
        data:
          temperature: "{{ states('input_number.house_target_low_temperature') | float(0) }}"
    else:
      - action: climate.set_hvac_mode
        target:
          entity_id: !input hvac_unit
        data:
          hvac_mode: cool
      - action: climate.set_temperature
        target:
          entity_id: !input hvac_unit
        data:
          temperature: "{{ states('input_number.house_target_high_temperature') | float(0) }}"

  - action: climate.set_fan_mode
    data:
      fan_mode: auto
    target:
      entity_id: !input hvac_unit

  - action: climate.set_swing_mode
    data:
      swing_mode: swing
    target:
      entity_id: !input hvac_unit