blueprint:
  domain: script
  name: "[HVAC] Dehumidifier Routine"
  input:
    hvac_entitiy:
      name: Ar Condicionado
      selector:
        entity:
          multiple: false
          filter:
            - domain: climate
    temperature_sensor:
      name: Sensor Temperatura
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              device_class: temperature
    heat_after:
      name: Aquecer
      default: "off"
      selector:
        boolean:

mode: restart

variables:
  heat_after: !input heat_after

sequence:
  - action: climate.set_temperature
    continue_on_error: true
    data:
      temperature: 18
    target:
      entity_id: !input hvac_entitiy

  - action: climate.set_hvac_mode
    data:
      hvac_mode: dry
    target:
      entity_id: !input hvac_entitiy

  - wait_for_trigger:
      - trigger: climate.hvac_mode_changed
        target:
          entity_id: !input hvac_entitiy
        options:
          behavior: all
          hvac_mode:
            - heat
            - heat_cool
            - cool
            - "off"
            - fan_only
    timeout:
      hours: 1
      minutes: 30
    continue_on_timeout: true

  - condition: not
    conditions:
      - condition: climate.is_off
        options:
          behavior: all
        target:
          entity_id: !input hvac_entitiy

  - delay: 10

  - if:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ not heat_after }}"
          - condition: temperature.is_value
            target:
              entity_id: !input temperature_sensor
            options:
              threshold:
                type: above
                value:
                  active_choice: number
                  number: 20
                  unit_of_measurement: °C
              behavior: all
    then:
      - action: climate.turn_off
        target:
          entity_id: !input hvac_entitiy
        data: {}
      - action: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: "off"
        target:
          entity_id: !input hvac_entitiy
      - action: climate.set_temperature
        continue_on_error: true
        data:
          temperature: 20
        target:
          entity_id: !input hvac_entitiy
      - stop: ""

  - action: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id: !input hvac_entitiy

  - delay: 10

  - action: climate.set_temperature
    continue_on_error: true
    data:
      temperature: 20
    target:
      entity_id: !input hvac_entitiy

  - wait_for_trigger:
      - trigger: climate.hvac_mode_changed
        target:
          entity_id: !input hvac_entitiy
        options:
          behavior: all
          hvac_mode:
            - heat
            - heat_cool
            - cool
            - "off"
            - fan_only
      - trigger: temperature.crossed_threshold
        target:
          entity_id: !input temperature_sensor
        options:
          threshold:
            type: above
            value:
              active_choice: number
              number: 20.3
              unit_of_measurement: °C
          behavior: all
    timeout:
      minutes: 30
    continue_on_timeout: true

  - action: climate.turn_off
    target:
      entity_id: !input hvac_entitiy
    data: {}

  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: "off"
    target:
      entity_id: !input hvac_entitiy
