substitutions:
  devicename: phosphorus

esphome:
  name: ${devicename}
  friendly_name: Phosphorus

esp32:
  board: nodemcu-32s
  framework:
    #type: arduino
    type: esp-idf
    version: recommended

packages:
  - !include ../packages/common.yml
  - !include ../packages/webserver.yml
  - !include ../packages/home_state.yml
  - !include deye_hybrid_1p.yaml
  - !include deye_fan_controller.yaml
  - !include water_heater_solar_panel.yaml


# esp32_ble_tracker:
#   scan_parameters:
#     interval: 320ms
#     window: 100ms
#     active: true

bluetooth_proxy:

sensor:
#   - platform: ble_scanner
#     id: ble_laundry
#     name: BLE Scanner Laundry

wifi:
  use_address: 10.20.107.151

# logger:
#   #level: INFO
#   level: DEBUG
# #   logs:
# #     modbus_controller: ERROR
# #     sensor: ERROR
# #     number: ERROR
# #     time: ERROR