substitutions:
  devicename: blitzwolf-ss4-bathroom-rc-fan

packages:
  esphome_base: !include packages/common.yml
  esphome_web: !include packages/webserver.yml

esphome:
  friendly_name: BlitzWolf SS4 Bathrom RC Fan
  includes:
    - <espnow.h>

esp8266:
  board: esp01_1m

fan:
  - id: fan_1
    name: Bathroom RC
    platform: binary
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    id: relay_1
    pin: GPIO05


globals:
  - id: espnow_toggle_fan
    type: bool
    restore_value: no
    initial_value: 'false'

wifi:
  on_connect:
    then:
      - lambda: |-
          esp_now_deinit();

          if (esp_now_init() != 0) {
            ESP_LOGE("espnow", "ESP-NOW init failed");
            return;
          }

          esp_now_set_self_role(ESP_NOW_ROLE_SLAVE);

          esp_now_register_recv_cb(
            [](uint8_t *mac, uint8_t *data, uint8_t len) {
              if (len < 1)
                return;

              ESP_LOGD(
                "espnow",
                "RX %02X:%02X:%02X:%02X:%02X:%02X command=%u",
                mac[0], mac[1], mac[2],
                mac[3], mac[4], mac[5],
                data[0]
              );

              if (data[0] == 0x01)
                id(espnow_toggle_fan) = true;
            }
          );

          ESP_LOGI("espnow", "ESP-NOW receiver initialized");




interval:
  - interval: 500ms
    then:
      - if:
          condition:
            lambda: |-
              return id(espnow_toggle_fan);
          then:
            - lambda: |-
                id(espnow_toggle_fan) = false;
            - fan.toggle: fan_1