substitutions:
  devicename: blitzwolf-ss4-bathroom-rc-fan

packages:
  esphome_base: !include packages/common.yml
  esphome_web: !include packages/webserver.yml

esphome:
  friendly_name: BlitzWolf SS4 Bathrom RC Fan

esp8266:
  board: esp01_1m

fan:
  - id: fan_1
    name: Bathroom RC
    platform: binary
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    id: relay_1
    pin: GPIO05
