substitutions:
  devicename: nodemcu_gate

esphome:
  friendly_name: NodeMCU do Portão

# esp8266:
#   board: nodemcuv2
#   early_pin_init: false

esp32:
  board: nodemcu-32s
  framework:
    #type: arduino
    type: esp-idf
    version: recommended

packages:
  esphome_base: !include packages/common.yml
  esphome_web: !include packages/webserver.yml

external_components:
  - source:
      type: local
      path: components/
    components: [sc_cover]

output:
  - platform: gpio
    id: relay_1
    pin:
      number: GPIO25
  - platform: gpio
    id: relay_2
    pin:
      number: GPIO26

binary_sensor:
  - platform: gpio
    id: gate_close_sensor
    name: gate_close
    pin:
      inverted: true
      number: GPIO32
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 250ms

  - platform: gpio
    id: gate_open_sensor
    name: gate_open
    pin:
      number: GPIO33
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 250ms

  - platform: gpio
    id: gate_ir
    name: gate_ir
    pin:
      inverted: false
      number: GPIO27
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 250ms
      - delayed_off: 2s

# switch:
#   - platform: output
#     name: relay_1
#     output: "relay_1"

#   - platform: output
#     name: relay_2
#     output: "relay_2"

sensor:
  - platform: homeassistant
    id: main_power
    entity_id: sensor.device_power_gate

button:
  # - platform: template
  #   id: gate_open_single_ha
  #   name: Gate Open Single (HA)
  #   on_press:
  #     then:
  #       #- lambda: "id(gate)->trigger_half_open();"
  #       - button.press: gate_open_single

  - platform: template
    id: gate_close
    name: Gate Close
    on_press:
      then:
        - cover.close: gate

  - platform: output
    id: gate_open_single
    name: Gate Open Single
    output: relay_2
    duration: 750ms

  - platform: output
    id: gate_open
    name: Gate Open
    output: relay_1
    duration: 750ms

cover:
  - platform: sc_cover
    name: "Gate"
    id: gate
    device_class: gate
    door_activate_button: gate_open
    half_activate_button: gate_open_single
    button_press_interval: 1500ms
    open_endstop: gate_open_sensor
    close_endstop: gate_close_sensor
    open_duration: 17s
    close_duration: 20s
    setup_delay: 2s


# logger:
#   level: DEBUG

wifi:
  use_address: 10.20.107.75