substitutions:
  devicename: shelly25-exterior-switches

packages:
  esphome_base: !include packages/common.yml
  esphome_web: !include packages/webserver.yml
  home_state: !include packages/home_state.yml

  device_base: !include
    file: packages/shelly25.yml
    vars:
      name: Shelly25 Exterior Switches

esphome:
  devices:
    - id: device_switch_1
      name: gate_door
    - id: exterior_flood_led
      name: exterior_flood_led

button:
  - platform: output
    id: gate_door_open
    output: relay_1
    duration: 2000ms

lock:
  - platform: template
    name: gate_door
    device_id: device_switch_1
    lambda: |-
      return LOCK_STATE_LOCKED;
    optimistic: true
    unlock_action:
      - button.press: gate_door_open

light:
  - id: light_1
    name: Exterior Flood Led
    device_id: exterior_flood_led
    platform: binary
    output: relay_2
    restore_mode: RESTORE_AND_OFF